# Site settings
title: In praise of randomness
email: axelexic@gmail.com
description: Decrypting modern cryptography
baseurl: ""
url: "http://axelexic.github.io"
twitter_username: axelexic
github_username:  axelexic
encoding: utf-8

# Build settings
markdown: kramdown
